//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BudgetDBEntities : DbContext
    {
        public BudgetDBEntities()
            : base("name=BudgetDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BudgetRecords> BudgetRecords { get; set; }
        public virtual DbSet<Budgets> Budgets { get; set; }
        public virtual DbSet<RecordGroups> RecordGroups { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
