//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetRecords
    {
        public int RecordID { get; set; }
        public Nullable<int> BudgetID { get; set; }
        public string RecordName { get; set; }
        public Nullable<int> RecordGroupID { get; set; }
        public Nullable<int> PlannedCost { get; set; }
        public Nullable<int> RealCost { get; set; }
        public string Comments { get; set; }
    
        public virtual Budgets Budgets { get; set; }
        public virtual RecordGroups RecordGroups { get; set; }
    }
}
